### PR TITLE
Relax `jupyterlab` constraint

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
IIUC this should be compatible with `jupyterlab >=4`
https://github.com/jupyterlab-contrib/rise/pull/42

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
```
import: 'jupyterlab_rise'
import: 'jupyterlab_rise'
+ pip check
No broken requirements found.
+ python -m jupyterlab.browser_check --no-chrome-test
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
usage: browser_check.py [-h] [--debug] [--show-config] [--show-config-json]
                        [--generate-config] [-y] [--allow-root] [--no-browser]
                        [--autoreload] [--script] [--no-script] [--core-mode]
                        [--dev-mode] [--skip-dev-build] [--watch]
                        [--splice-source] [--expose-app-in-browser]
                        [--extensions-in-dev-mode] [--collaborative]
                        [--log-level ServerApp.log_level]
                        [--config ServerApp.config_file] [--ip ServerApp.ip]
                        [--port ServerApp.port]
                        [--port-retries ServerApp.port_retries]
                        [--sock ServerApp.sock]
                        [--sock-mode ServerApp.sock_mode]
                        [--transport KernelManager.transport]
                        [--keyfile ServerApp.keyfile]
                        [--certfile ServerApp.certfile]
                        [--client-ca ServerApp.client_ca]
                        [--notebook-dir ServerApp.root_dir]
                        [--preferred-dir ServerApp.preferred_dir]
                        [--browser ServerApp.browser]
                        [--pylab ServerApp.pylab]
                        [--gateway-url GatewayClient.url]
                        [--app-dir BrowserApp.app_dir]
                        [extra_args ...]
browser_check.py: error: unrecognized arguments: --no-chrome-test
Tests failed for jupyterlab_rise-0.40.0-pyhd8ed1ab_1.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for jupyterlab_rise-0.40.0-pyhd8ed1ab_1.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by fcollonval** [comment]
Thanks a lot @dhirschfeld

**Pull request merged**
